// <auto-generated />
using System;
using DogoFinance.DataAccess.Layer.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogoFinance.DataAccess.Layer.Migrations
{
    [DbContext(typeof(DogoFinanceContext))]
    partial class DogoFinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblAccessRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("TBL_ACCESS_RIGHT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblAddressDocType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBL_ADDRESS_DOC_TYPE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblAssetClass", b =>
                {
                    b.Property<int>("AssetClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetClassId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsShariahCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AssetClassId");

                    b.ToTable("TBL_ASSET_CLASS");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblBank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"), 1L, 1);

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BankId");

                    b.ToTable("TBL_BANK");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("TBL_CHART_OF_ACCOUNT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("TBL_CURRENCY");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Bvn")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("BVN");

                    b.Property<bool>("Bvnverified")
                        .HasColumnType("bit")
                        .HasColumnName("BVNVerified");

                    b.Property<DateTime?>("BvnverifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("BVNVerifiedAt");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("('Nigeria')");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPolitcallyExposed")
                        .HasColumnType("bit");

                    b.Property<int>("Kycstatus")
                        .HasColumnType("int")
                        .HasColumnName("KYCStatus");

                    b.Property<DateTime?>("KycverifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("KYCVerifiedAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Nin")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("NIN");

                    b.Property<bool>("Ninverified")
                        .HasColumnType("bit")
                        .HasColumnName("NINVerified");

                    b.Property<DateTime?>("NinverifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NINVerifiedAt");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CustomerId")
                        .HasName("PK__TBL_CUST__A4AE64D8B9B6FDD4");

                    b.HasIndex(new[] { "Bvn" }, "IX_TBL_CUSTOMER_BVN")
                        .IsUnique()
                        .HasFilter("([BVN] IS NOT NULL)");

                    b.HasIndex(new[] { "Nin" }, "IX_TBL_CUSTOMER_NIN")
                        .IsUnique()
                        .HasFilter("([NIN] IS NOT NULL)");

                    b.HasIndex(new[] { "UserId" }, "IX_TBL_CUSTOMER_UserId")
                        .IsUnique();

                    b.ToTable("TBL_CUSTOMER");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerAddressVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CloudinaryPublicId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtractedAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtractedCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtractedFullText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ExtractedState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocTypeId");

                    b.ToTable("TBL_CUSTOMER_ADDRESS_VERIFICATION");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerBank", b =>
                {
                    b.Property<long>("CustomerBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerBankId"), 1L, 1);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CustomerBankId");

                    b.HasIndex("BankId");

                    b.HasIndex("CustomerId");

                    b.ToTable("TBL_CUSTOMER_BANK");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerHolding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("TBL_CUSTOMER_HOLDING");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerPortfolio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TBL_CUSTOMER_PORTFOLIO");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblGender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBL_GENDER", (string)null);
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsShariahCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("InstrumentId");

                    b.ToTable("TBL_INSTRUMENT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrumentPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("NAV")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriceSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("TBL_INSTRUMENT_PRICE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblInvestmentTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("NAV")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TBL_INVESTMENT_TRANSACTION");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblJournalEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TBL_JOURNAL_ENTRY");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblJournalLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("JournalEntryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("TBL_JOURNAL_LINE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblKycLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TBL_KYC_LOG");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Narration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBL_LEDGER");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblLiquidationRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ExitFeeApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpectedReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPayableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("UnitsRequested")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("TBL_LIQUIDATION_REQUEST");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBL_MODULE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblNextOfKin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RelationshipTypeId");

                    b.ToTable("TBL_NEXT_OF_KIN");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPasswordReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_PASSWORD_RESET");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentProvider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_PAYMENT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPinReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_PIN_RESET");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", b =>
                {
                    b.Property<int>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioId"), 1L, 1);

                    b.Property<decimal>("ApprovalThresholdAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExitFeePercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ExpectedAnnualReturn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("LockInPeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("MinHoldingPeriodDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NoticePeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PortfolioId");

                    b.HasIndex("PortfolioTypeId");

                    b.ToTable("TBL_PORTFOLIO");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioAllocationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssetClassId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaxPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TBL_PORTFOLIO_ALLOCATION_RULE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssetClassId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetWeight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TBL_PORTFOLIO_INSTRUMENT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NAV")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TBL_PORTFOLIO_PRICE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioType", b =>
                {
                    b.Property<int>("PortfolioTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioTypeId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("SupportsAllocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("PortfolioTypeId");

                    b.ToTable("TBL_PORTFOLIO_TYPE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBL_RELATIONSHIP_TYPE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblReservedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_RESERVED_ACCOUNT");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBL_ROLE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRoleAccessRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessRightId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessRightId");

                    b.HasIndex("RoleId");

                    b.ToTable("TBL_ROLE_ACCESS_RIGHT", (string)null);
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblSystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SessionTimeoutInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WithdrawalAutoThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TBL_SYSTEM_SETTING", (string)null);
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("InitiatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("Narration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ReversedTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId")
                        .HasName("PK__TBL_TRAN__55433A6BBD1D0E19");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReversedTransactionId");

                    b.ToTable("TBL_TRANSACTION");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBL_TRANSACTION_TYPE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Is2faEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinSet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPinChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PinFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransactionPinHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionPinSalt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("VerificationExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK__TBL_USER__1788CC4C596A566F");

                    b.HasIndex(new[] { "Email" }, "IX_TBL_USER_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_TBL_USER_PhoneNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "IX_TBL_USER_UserName")
                        .IsUnique();

                    b.ToTable("TBL_USER");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_USER_ROLE");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUserSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_USER_SESSION");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblWallet", b =>
                {
                    b.Property<long>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WalletId"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("WalletId")
                        .HasName("PK__TBL_WALL__84D4F90E05132222");

                    b.HasIndex("CustomerId");

                    b.ToTable("TBL_WALLET");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblWithdrawalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Narration")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("TBL_WITHDRAWAL_REQUEST");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblAccessRight", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblModule", "Module")
                        .WithMany("TblAccessRights")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithOne("TblCustomer")
                        .HasForeignKey("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TBL_CUSTOMER_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerAddressVerification", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany("TblCustomerAddressVerifications")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_ADDR_VERIF_CUSTOMER");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblAddressDocType", "DocType")
                        .WithMany("TblCustomerAddressVerifications")
                        .HasForeignKey("DocTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ADDR_VERIF_DOCTYPE");

                    b.Navigation("Customer");

                    b.Navigation("DocType");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerBank", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblBank", "Bank")
                        .WithMany("TblCustomerBanks")
                        .HasForeignKey("BankId")
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_BANK_BANK");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany("TblCustomerBanks")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_BANK_CUSTOMER");

                    b.Navigation("Bank");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerHolding", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomerPortfolio", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrumentPrice", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblInvestmentTransaction", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblJournalLine", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblChartOfAccount", "Account")
                        .WithMany("JournalLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblJournalEntry", "JournalEntry")
                        .WithMany("JournalLines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblKycLog", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany("TblKycLogs")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_KYC_CUSTOMER");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblLiquidationRequest", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.Navigation("Customer");

                    b.Navigation("Portfolio");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblNextOfKin", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany("TblNextOfKins")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_NEXT_OF_KIN_CUSTOMER");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblRelationshipType", "RelationshipType")
                        .WithMany("TblNextOfKins")
                        .HasForeignKey("RelationshipTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_NEXT_OF_KIN_RELATIONSHIP");

                    b.Navigation("Customer");

                    b.Navigation("RelationshipType");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPasswordReset", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany("TblPasswordResets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PASSWORD_RESET_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPayment", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany("TblPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PAYMENT_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPinReset", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioType", "PortfolioType")
                        .WithMany()
                        .HasForeignKey("PortfolioTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioType");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioAllocationRule", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblAssetClass", "AssetClass")
                        .WithMany()
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetClass");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioInstrument", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblAssetClass", "AssetClass")
                        .WithMany()
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblInstrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetClass");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolioPrice", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPortfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblReservedAccount", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRoleAccessRight", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblAccessRight", "AccessRight")
                        .WithMany()
                        .HasForeignKey("AccessRightId")
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("AccessRight");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblTransaction", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "ApprovedByUser")
                        .WithMany("TblTransactionApprovedByUsers")
                        .HasForeignKey("ApprovedByUserId")
                        .HasConstraintName("FK_TXN_USER_APPROVE");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "InitiatedByUser")
                        .WithMany("TblTransactionInitiatedByUsers")
                        .HasForeignKey("InitiatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_TXN_USER_INIT");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblPayment", "Payment")
                        .WithMany("TblTransactions")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_TXN_PAYMENT");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblTransaction", "ReversedTransaction")
                        .WithMany("InverseReversedTransaction")
                        .HasForeignKey("ReversedTransactionId")
                        .HasConstraintName("FK_TXN_REVERSAL");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("Payment");

                    b.Navigation("ReversedTransaction");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUserRole", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblRole", "Role")
                        .WithMany("TblUserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_ROLE");

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany("TblUserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_USER");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUserSession", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblWallet", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany("TblWallets")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_WALLET_CUSTOMER");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblWithdrawalRequest", b =>
                {
                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", "Admin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.Navigation("Admin");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblAddressDocType", b =>
                {
                    b.Navigation("TblCustomerAddressVerifications");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblBank", b =>
                {
                    b.Navigation("TblCustomerBanks");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblChartOfAccount", b =>
                {
                    b.Navigation("JournalLines");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblCustomer", b =>
                {
                    b.Navigation("TblCustomerAddressVerifications");

                    b.Navigation("TblCustomerBanks");

                    b.Navigation("TblKycLogs");

                    b.Navigation("TblNextOfKins");

                    b.Navigation("TblWallets");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblJournalEntry", b =>
                {
                    b.Navigation("JournalLines");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblModule", b =>
                {
                    b.Navigation("TblAccessRights");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblPayment", b =>
                {
                    b.Navigation("TblTransactions");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRelationshipType", b =>
                {
                    b.Navigation("TblNextOfKins");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblRole", b =>
                {
                    b.Navigation("TblUserRoles");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblTransaction", b =>
                {
                    b.Navigation("InverseReversedTransaction");
                });

            modelBuilder.Entity("DogoFinance.DataAccess.Layer.Models.Entities.TblUser", b =>
                {
                    b.Navigation("TblCustomer")
                        .IsRequired();

                    b.Navigation("TblPasswordResets");

                    b.Navigation("TblPayments");

                    b.Navigation("TblTransactionApprovedByUsers");

                    b.Navigation("TblTransactionInitiatedByUsers");

                    b.Navigation("TblUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
